<a href="https://colab.research.google.com/github/JulianBasilio/58013-Linear-Algebra/blob/main/LongQuiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
A



array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
B= np.array([[1,2],[3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
D= np.array([[1,2],[3,4]])
D

array([[1, 2],
       [3, 4]])

In [25]:
### 1) AB
A1 = A
B1= np.arange(0,6).reshape(2,3)
B1

AB= A1 * B1
AB

array([[ 0,  2,  6],
       [12, 20, 30]])

In [26]:
### 2) D+D
D+D

array([[2, 4],
       [6, 8]])

In [33]:
### 3) 2C
2 * C


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
A= np.array([2,7,4])
B= np.array([3,9,8])
np.cross(A,B)

array([20, -4, -3])