<a href="https://colab.research.google.com/github/JulianBasilio/58013-Linear-Algebra/blob/main/Python_Exercise10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [17]:
### Coding Activity
### A= value of products
A= [(
    [30,10,120],
    [40,20,200],
    [50,40,360]
)]
dA= np.linalg.det(A)

B= [([12500],
    [18000],
    [25700],
)]
A1= [(
    [12500,10,120],
    [18000,20,200],
    [25700,40,360]
)]

A2= [(
    [30,12500,120],
    [40,18000,200],
    [50,25700,360]
)]

A3= [(
    [30,10,12500],
    [40,20,18000],
    [50,40,25700]
)]
dA1= np.linalg.det(A1)
dA2= np.linalg.det(A2)
dA3= np.linalg.det(A3)
x= dA1+dA2+dA3

flour= dA1/dA
yeast= dA2/dA
egg= dA3/dA

print("The price of flour per sack is",flour,"pesos")
print("The price of yeast per pack is",yeast,"pesos")
print("The price of a piece of egg is",egg,"pesos")


The price of flour per sack is [330.] pesos
The price of yeast per pack is [140.] pesos
The price of a piece of egg is [10.] pesos
