<a href="https://colab.research.google.com/github/JulianBasilio/58013-Linear-Algebra/blob/main/Vectors%2C_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
A = np.array([4,3])
B = np.array([2, -5])
print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [65]:
#Side Dimension, Size
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
ball = np.array(ball1)
balls= np.array(ball2)
z= ball+balls
print(z)




[1 3 2]


In [58]:
#Addition
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])
R = np.add(A,B)
print(R)

[ 6 -2]


In [61]:
#Subtraction
R1 = np.subtract(A,B)
print(R1)
R2= np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


In [72]:
#Scalar Product
import numpy as np
S = np.array([2])
V = S*A
print(V)

[8 6]


In [69]:
#Dot Product
a= np.array([2])
b= np.array([4])
c= np.dot(a,b)
print(c)

8


In [87]:
#Cross Product
import numpy as np
#initialize arrays
W = np.array([2, 3])
X = np.array([1, 7])
#compute cross product
output = np.cross(W, X)
print(output)

11


In [90]:
#Property of Matrix
#Identity Matrix
c= np.eye(3,3)
print(c)

#Zero Matrix
d= np.zeros([5,5])
print(d)

#Full Matrix
e= np.full([3,3],7)
print(e)

#Transpose Matrix
f= np.transpose(A)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[2 3]
